name: hitchmap-data
dependencies:
  - pip
  - python=3.10
  - pip:
    - datasets
    - folium
    - geopandas
    - ipykernel
    - ipython
    - matplotlib
    - numpy
    - osmnx
    - pandas
    - scikit-learn
    - scipy
    - shapely
    - tqdm
    - lingua-language-detector
