name: hitchhiking-data
dependencies:
  - pip
  - python=3.10
  - pip:
    - datasets
    - dotenv
    - folium==0.19.6
    - geopandas
    - heatchmap
    - huggingface_hub
    - ipykernel
    - ipython
    - matplotlib
    - numpy
    - osmnx
    - pandas
    - pycountry
    - pydantic
    - scikit-learn
    - scipy
    - seaborn
    - shapely
    - tqdm
    - typing_extensions
    - lingua-language-detector
    - worldmap
