name: paper
dependencies:
  - pip
  - python=3.10
  - pip:
    - datasets==3.6.0
    - dotenv==0.9.9
    - huggingface_hub==0.33.0
    - ipykernel==6.29.5
    - matplotlib==3.10.3
    - pandas==2.3.0
    - pycountry==24.6.1
    - pydantic==2.11.7
    - seaborn==0.13.2
    - tqdm==4.67.1
    - typing_extensions==4.14.0
    - lingua-language-detector==2.1.1
    - worldmap==0.1.7